/* Auto-generated by genmsg_cpp for file /opt/ros/hydro/share/Butia/srv/ButiaGetGray.srv */
#ifndef BUTIA_SERVICE_BUTIAGETGRAY_H
#define BUTIA_SERVICE_BUTIAGETGRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace Butia
{
template <class ContainerAllocator>
struct ButiaGetGrayRequest_ {
  typedef ButiaGetGrayRequest_<ContainerAllocator> Type;

  ButiaGetGrayRequest_()
  : a(0)
  {
  }

  ButiaGetGrayRequest_(const ContainerAllocator& _alloc)
  : a(0)
  {
  }

  typedef int64_t _a_type;
  int64_t a;


  typedef boost::shared_ptr< ::Butia::ButiaGetGrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Butia::ButiaGetGrayRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ButiaGetGrayRequest
typedef  ::Butia::ButiaGetGrayRequest_<std::allocator<void> > ButiaGetGrayRequest;

typedef boost::shared_ptr< ::Butia::ButiaGetGrayRequest> ButiaGetGrayRequestPtr;
typedef boost::shared_ptr< ::Butia::ButiaGetGrayRequest const> ButiaGetGrayRequestConstPtr;



template <class ContainerAllocator>
struct ButiaGetGrayResponse_ {
  typedef ButiaGetGrayResponse_<ContainerAllocator> Type;

  ButiaGetGrayResponse_()
  : value(0)
  {
  }

  ButiaGetGrayResponse_(const ContainerAllocator& _alloc)
  : value(0)
  {
  }

  typedef int64_t _value_type;
  int64_t value;


  typedef boost::shared_ptr< ::Butia::ButiaGetGrayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Butia::ButiaGetGrayResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ButiaGetGrayResponse
typedef  ::Butia::ButiaGetGrayResponse_<std::allocator<void> > ButiaGetGrayResponse;

typedef boost::shared_ptr< ::Butia::ButiaGetGrayResponse> ButiaGetGrayResponsePtr;
typedef boost::shared_ptr< ::Butia::ButiaGetGrayResponse const> ButiaGetGrayResponseConstPtr;


struct ButiaGetGray
{

typedef ButiaGetGrayRequest Request;
typedef ButiaGetGrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ButiaGetGray
} // namespace Butia

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Butia::ButiaGetGrayRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Butia::ButiaGetGrayRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Butia::ButiaGetGrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const  ::Butia::ButiaGetGrayRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::Butia::ButiaGetGrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Butia/ButiaGetGrayRequest";
  }

  static const char* value(const  ::Butia::ButiaGetGrayRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Butia::ButiaGetGrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 a\n\
\n\
";
  }

  static const char* value(const  ::Butia::ButiaGetGrayRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Butia::ButiaGetGrayRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Butia::ButiaGetGrayResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Butia::ButiaGetGrayResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Butia::ButiaGetGrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6dd7c3e2ac5f4efb95e3dafd2085a161";
  }

  static const char* value(const  ::Butia::ButiaGetGrayResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6dd7c3e2ac5f4efbULL;
  static const uint64_t static_value2 = 0x95e3dafd2085a161ULL;
};

template<class ContainerAllocator>
struct DataType< ::Butia::ButiaGetGrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Butia/ButiaGetGrayResponse";
  }

  static const char* value(const  ::Butia::ButiaGetGrayResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Butia::ButiaGetGrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 value\n\
\n\
\n\
";
  }

  static const char* value(const  ::Butia::ButiaGetGrayResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Butia::ButiaGetGrayResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Butia::ButiaGetGrayRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.a);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ButiaGetGrayRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Butia::ButiaGetGrayResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ButiaGetGrayResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<Butia::ButiaGetGray> {
  static const char* value() 
  {
    return "7f3e10264ccd535f5708d53bf708e428";
  }

  static const char* value(const Butia::ButiaGetGray&) { return value(); } 
};

template<>
struct DataType<Butia::ButiaGetGray> {
  static const char* value() 
  {
    return "Butia/ButiaGetGray";
  }

  static const char* value(const Butia::ButiaGetGray&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Butia::ButiaGetGrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7f3e10264ccd535f5708d53bf708e428";
  }

  static const char* value(const Butia::ButiaGetGrayRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Butia::ButiaGetGrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Butia/ButiaGetGray";
  }

  static const char* value(const Butia::ButiaGetGrayRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Butia::ButiaGetGrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7f3e10264ccd535f5708d53bf708e428";
  }

  static const char* value(const Butia::ButiaGetGrayResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Butia::ButiaGetGrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Butia/ButiaGetGray";
  }

  static const char* value(const Butia::ButiaGetGrayResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // BUTIA_SERVICE_BUTIAGETGRAY_H

