/* Auto-generated by genmsg_cpp for file /opt/ros/hydro/share/Butia/srv/ButiaGetDistance.srv */
#ifndef BUTIA_SERVICE_BUTIAGETDISTANCE_H
#define BUTIA_SERVICE_BUTIAGETDISTANCE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace Butia
{
template <class ContainerAllocator>
struct ButiaGetDistanceRequest_ {
  typedef ButiaGetDistanceRequest_<ContainerAllocator> Type;

  ButiaGetDistanceRequest_()
  : a(0)
  {
  }

  ButiaGetDistanceRequest_(const ContainerAllocator& _alloc)
  : a(0)
  {
  }

  typedef int64_t _a_type;
  int64_t a;


  typedef boost::shared_ptr< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ButiaGetDistanceRequest
typedef  ::Butia::ButiaGetDistanceRequest_<std::allocator<void> > ButiaGetDistanceRequest;

typedef boost::shared_ptr< ::Butia::ButiaGetDistanceRequest> ButiaGetDistanceRequestPtr;
typedef boost::shared_ptr< ::Butia::ButiaGetDistanceRequest const> ButiaGetDistanceRequestConstPtr;



template <class ContainerAllocator>
struct ButiaGetDistanceResponse_ {
  typedef ButiaGetDistanceResponse_<ContainerAllocator> Type;

  ButiaGetDistanceResponse_()
  : value(0)
  {
  }

  ButiaGetDistanceResponse_(const ContainerAllocator& _alloc)
  : value(0)
  {
  }

  typedef int64_t _value_type;
  int64_t value;


  typedef boost::shared_ptr< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ButiaGetDistanceResponse
typedef  ::Butia::ButiaGetDistanceResponse_<std::allocator<void> > ButiaGetDistanceResponse;

typedef boost::shared_ptr< ::Butia::ButiaGetDistanceResponse> ButiaGetDistanceResponsePtr;
typedef boost::shared_ptr< ::Butia::ButiaGetDistanceResponse const> ButiaGetDistanceResponseConstPtr;


struct ButiaGetDistance
{

typedef ButiaGetDistanceRequest Request;
typedef ButiaGetDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ButiaGetDistance
} // namespace Butia

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const  ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Butia/ButiaGetDistanceRequest";
  }

  static const char* value(const  ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 a\n\
\n\
";
  }

  static const char* value(const  ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6dd7c3e2ac5f4efb95e3dafd2085a161";
  }

  static const char* value(const  ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6dd7c3e2ac5f4efbULL;
  static const uint64_t static_value2 = 0x95e3dafd2085a161ULL;
};

template<class ContainerAllocator>
struct DataType< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Butia/ButiaGetDistanceResponse";
  }

  static const char* value(const  ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 value\n\
\n\
\n\
";
  }

  static const char* value(const  ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Butia::ButiaGetDistanceRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.a);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ButiaGetDistanceRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Butia::ButiaGetDistanceResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ButiaGetDistanceResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<Butia::ButiaGetDistance> {
  static const char* value() 
  {
    return "7f3e10264ccd535f5708d53bf708e428";
  }

  static const char* value(const Butia::ButiaGetDistance&) { return value(); } 
};

template<>
struct DataType<Butia::ButiaGetDistance> {
  static const char* value() 
  {
    return "Butia/ButiaGetDistance";
  }

  static const char* value(const Butia::ButiaGetDistance&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Butia::ButiaGetDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7f3e10264ccd535f5708d53bf708e428";
  }

  static const char* value(const Butia::ButiaGetDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Butia::ButiaGetDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Butia/ButiaGetDistance";
  }

  static const char* value(const Butia::ButiaGetDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Butia::ButiaGetDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7f3e10264ccd535f5708d53bf708e428";
  }

  static const char* value(const Butia::ButiaGetDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Butia::ButiaGetDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Butia/ButiaGetDistance";
  }

  static const char* value(const Butia::ButiaGetDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // BUTIA_SERVICE_BUTIAGETDISTANCE_H

